server:
  port: ${SERVER_PORT}
spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  devtools:
    restart:
      enabled: true
  security:
    user:
      name: quyet
      password: 12345

logging:
  level:
    com.fasterxml.jackson.databind: DEBUG
# RestTemplate timeouts (đọc bởi RestTemplateConfig)
resttemplate:
  connect-timeout: 5s   # thời gian chờ thiết lập kết nối
  read-timeout: 10s     # thời gian chờ đọc dữ liệu (response)
